
package ProductPrices;


public class ProductPriceForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductPriceForm.class.getName());

    /**
     * Creates new form ProductPriceForm
     */
    public ProductPriceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitle = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelPrice = new javax.swing.JLabel();
        LabelQuantity = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        FieldPrice = new javax.swing.JTextField();
        FieldQuantity = new javax.swing.JTextField();
        ButtonPrice = new javax.swing.JButton();
        LabelOutput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelTitle.setText("Product Price Calculator");

        LabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelName.setText("Product Name :");

        LabelPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelPrice.setText("Unit Price :");

        LabelQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelQuantity.setText("Quantity :");

        FieldName.addActionListener(this::FieldNameActionPerformed);

        ButtonPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ButtonPrice.setText("Calculate Price");
        ButtonPrice.addActionListener(this::ButtonPriceActionPerformed);

        LabelOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelOutput.setText("Output :");

        AreaOutput.setColumns(20);
        AreaOutput.setRows(5);
        jScrollPane1.setViewportView(AreaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(LabelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(ButtonPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LabelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FieldName)
                                    .addComponent(FieldPrice)
                                    .addComponent(FieldQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrice))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelQuantity)
                    .addComponent(FieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelOutput)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNameActionPerformed

    private void ButtonPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPriceActionPerformed
        // TODO add your handling code here:
        // 1. Read input values safely from the UI user entry text fields [cite: 16, 419]
        String productName = FieldName.getText();
        double unitPrice = Double.parseDouble(FieldPrice.getText());
        int quantity = Integer.parseInt(FieldQuantity.getText());
        
        // 2. Create the external domain class blueprint object [cite: 17, 419]
        Product myProduct = new Product(productName, unitPrice, quantity);
        
        // 3. Request logic determinations back from the object and format the text block [cite: 18, 419]
        String result = "Product Name: " + myProduct.getProductName() + "\n" +
                        "Unit Price: " + myProduct.getUnitPrice() + "\n" +
                        "Quantity: " + myProduct.getQuantity() + "\n" +
                        "Total Price: " + myProduct.calculateTotal() + "\n" +
                        "Stock Status: " + myProduct.getStockStatus(); // [cite: 483, 484, 485, 486, 487]
        
        // 4. Print clean structured string down into the text area component [cite: 18, 419]
        AreaOutput.setText(result);
    }//GEN-LAST:event_ButtonPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductPriceForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaOutput;
    private javax.swing.JButton ButtonPrice;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldPrice;
    private javax.swing.JTextField FieldQuantity;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelOutput;
    private javax.swing.JLabel LabelPrice;
    private javax.swing.JLabel LabelQuantity;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
