
package MembershipRegistration;

/**
 *
 * @author Anuja Mewan
 */
public class RegistrationForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationForm.class.getName());

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TitleMembership = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelNumber = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        FieldNumber = new javax.swing.JTextField();
        ButtonRegular = new javax.swing.JRadioButton();
        ButtonPremium = new javax.swing.JRadioButton();
        CheckBoxNewsletter = new javax.swing.JCheckBox();
        ButtonRegistor = new javax.swing.JButton();
        LabelOutput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaOutput = new javax.swing.JTextArea();
        LabelType = new javax.swing.JLabel();
        Labelnewsletter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleMembership.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TitleMembership.setText("Membership Registration Form");

        LabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelName.setText("Member Name :");

        LabelNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNumber.setText("Number Of Months :");

        ButtonRegular.setText("Regular");

        ButtonPremium.setText("Premium");
        ButtonPremium.addActionListener(this::ButtonPremiumActionPerformed);

        CheckBoxNewsletter.setText("Newsletter ");

        ButtonRegistor.setText("Register");
        ButtonRegistor.addActionListener(this::ButtonRegistorActionPerformed);

        LabelOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelOutput.setText("Output :");

        AreaOutput.setColumns(20);
        AreaOutput.setRows(5);
        jScrollPane1.setViewportView(AreaOutput);

        LabelType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelType.setText("Membership Type :");

        Labelnewsletter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Labelnewsletter.setText("Newsletter Subscription :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TitleMembership))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ButtonRegistor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelName)
                                .addGap(18, 18, 18)
                                .addComponent(FieldName))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Labelnewsletter, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CheckBoxNewsletter))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(LabelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(LabelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ButtonRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ButtonPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 14, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TitleMembership)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumber)
                    .addComponent(FieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegular)
                    .addComponent(ButtonPremium)
                    .addComponent(LabelType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelnewsletter)
                    .addComponent(CheckBoxNewsletter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonRegistor)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelOutput)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPremiumActionPerformed

    private void ButtonRegistorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistorActionPerformed
        // TODO add your handling code here:
        // 1. Read layout text box properties safely
        String name = FieldName.getText();
        int months = Integer.parseInt(FieldNumber.getText());
        boolean newsletterSelected = CheckBoxNewsletter.isSelected();
        
        // 2. Extract selected radio option string text context
        String membershipType = "Regular";
        if (ButtonPremium.isSelected()) {
            membershipType = "Premium";
        }
        
        // 3. Pass values to calculate the logic inside the OOP Class
        Member member = new Member(name, membershipType, newsletterSelected, months);
        
        // 4. Extract data and print formatted output lines
        String summary = "Member Name: " + member.getMemberName() + "\n" +
                         "Membership Type: " + member.getMembershipType() + "\n" +
                         "Months: " + member.getNumberOfMonths() + "\n" +
                         "Newsletter: " + member.getNewsletterText() + "\n" +
                         "Total Fee: " + member.getMembershipFee();
        
        AreaOutput.setText(summary);
    }//GEN-LAST:event_ButtonRegistorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaOutput;
    private javax.swing.JRadioButton ButtonPremium;
    private javax.swing.JButton ButtonRegistor;
    private javax.swing.JRadioButton ButtonRegular;
    private javax.swing.JCheckBox CheckBoxNewsletter;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldNumber;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelNumber;
    private javax.swing.JLabel LabelOutput;
    private javax.swing.JLabel LabelType;
    private javax.swing.JLabel Labelnewsletter;
    private javax.swing.JLabel TitleMembership;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
